In [8]:
import pandas as pd
import re

def extract_text_in_parentheses(text):
    match = re.search(r'\((.*?)\)', text)
    if match:
        return match.group(1)
    else:
        return ''

input_file1 = 'ExperimentalHEB6.xlsx'
df1 = pd.read_excel(input_file1)
materials1 = df1.iloc[:, 0]
synthe = df1.iloc[:, 1]
# print(synthe)  

materials_list1 = []
for material in materials1:
    materials_i = extract_text_in_parentheses(material)
    materials_list1.append(materials_i)
# print(','.join(materials_list1))

input_file = 'HEB6.xlsx'
df = pd.read_excel(input_file)
df_copy = df.copy()
materials = df.iloc[:, 0]
materials_list = []
for material in materials:
    materials_i = extract_text_in_parentheses(material)
    materials_list.append(materials_i)

# input_text = input("Please input quinary HEB6 selected form Be, Mg, Ca, Sr, Ba, Sc, Y and lanthanide (excluding radioactive element), eg.BeMgCaSrLa,BeMgCaSrBa")
input_text = ','.join(materials_list1)
elements_list = input_text.split(",")

merged_df = pd.DataFrame()
for i in range(len(elements_list)):
    elements_list_i = re.findall('[A-Z][^A-Z]*', elements_list[i])
    a = set(elements_list_i)
    for j in range(len(materials_list)):
        materials_list_i = re.findall('[A-Z][^A-Z]*', materials_list[j])
        b = set(materials_list_i)
        if a == b:
            df_j = df.iloc[j, :]
            merged_df = pd.concat([merged_df, df_j], axis=1)
            print(j)
            df_modified = df_copy.drop(j, axis=0)
#             print(df.loc[j, 'Experiments'])
#             df.loc[j, 'Experiments'] = synthe[i]

# print(df_copy)
df_copy.to_csv('HEB6nwe.csv')
merged_df.T.to_excel('SearchResults.xlsx')

# merged_df.T

3382
3751
4047
3368
2304
5842
1914
3783
2635
3847
5913
4379
16666
15185
4400
4247
6780
4645
5354
4159
6651
4770
3978
2017
11624
1749
5237
3692
6511
4794
10286
12794
16472
14148
10674
11381
16494
11403
15366
15786
11074
12991
19314
10381
14123
16704
11480
12525
13135
5676
12027
15937
10696
12688
16688
11241
14872
12033
15880
10413
14743
17037
11901
16063
12933
15078
17917
12220
14616
17023
11713
5668
19959
16775
10893
13763
16781
10895
14389
17276
12147
16428
18480
13534
17258
12149
16037
19349
15267
19333
15353
11333
20103
17983
15250
19986
19387
19037
19091
12592

In [10]:
import pandas as pd

# 创建一个示例DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)

# 复制DataFrame
df_copy = df.copy()

# 输出原始DataFrame和复制后的DataFrame
print("原始DataFrame：")
print(df)
print("\n复制后的DataFrame：")
print(df.drop(1, axis=0))
print(df)

原始DataFrame：
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

复制后的DataFrame：
      Name  Age      City
0    Alice   25  New York
2  Charlie   35   Chicago
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago